### PR TITLE
Feature/moar boundaries

### PR DESCRIPTION
**Pull request by olafveerman**
…d/openroads#259

Finally ready for your review @DylanMoriarty

### CODE REVIEW

**Comment by DylanMoriarty** [comment]
great. Checking out now.

**Comment by DylanMoriarty** [comment]
or_Country is still offset from the rest of the files, but otherwise everything else lines up fine.

screenshot 2016-03-16 15 33 20

**Comment by olafveerman** [comment]
OK, will update that file as well

**Comment by olafveerman** [comment]
@DylanMoriarty Country files updated. Ready to review and merge.

**Comment by olafveerman** [comment]
Ready to be pulled in @DylanMoriarty ?

**Comment by olafveerman** [comment]
Can you check again @DylanMoriarty ?

**Comment by DylanMoriarty** [comment]
:tada: :+1: :tada:

**Pull request merged**
